#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u train_teacher.py "$@"

python -u train_student.py "$@"

# The previous version of this file was commented-out and follows below:
#
# python -u train_teacher.py "$@"
# 
